### ISSUE TITLE
Source Generator ArgumentNullException

### ISSUE THREAD

**Issue by jons-bakerhill** [NeVeSpl/NTypewriter#103]
With both 0.2.6 and 0.3.2 I get the following error during build:

`CSC : warning CS8785: Generator 'NTypewriterSourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'ArgumentNullException' with message 'Value cannot be null.`

The template runs fine using the VS extension.

I'm happy to do more troubleshooting, just not sure where to start.

------

Things stopped rendering altogether shortly after posting the above (possibly related to changing NuGet/VS Extension things) and I had to reboot to get templates to attempt to render again. I'd see "ProjectBuildDone event" but nothing would happen after that. Post reboot when I try to render by saving the template it tries again but now I get `13:10:03.127 ERROR: RpuQCc2 <input>(53,19) Unexpected exception while accessing target expression: Exception has been thrown by the target of an invocation.` where line 53 is `{{   for class in data.Classes #| Symbols.ThatHaveAttribute "ApiModel" -}}`

**Comment by NeVeSpl** [comment]
You need two instances of VS,
- one instance with loaded project that uses SG
- second one with opened SG source code

and you simply do : Debug -> Attach to process - from the second to the first instance of VS

**Comment by jons-bakerhill** [comment]
Haven't had any luck getting debugging working (yet) mostly following this https://github.com/JoanComasFdz/dotnet-how-to-debug-source-generator-vs2022 I was setting up for the attach when I noticed that the extension seemed fine after I uninstalled all the source generator nuget packages so I grabbed 1 of the 100+ projects and both the extension and the source generator appear to work with just that one so I guess I'll start binary searching the projects to see if I can figure out which one is making it blow up.

**Comment by NeVeSpl** [comment]
I have suspicion that the output path of one of yours projects may be null, this line would definitely throw exception in such a case: 

https://github.com/NeVeSpl/NTypewriter/blob/a854e6a3ccad7948f7427b6698dfe90977a51444/NTypewriter.SourceGenerator/SourceGenerator.cs#L119

**Comment by NeVeSpl** [comment]
I think that all problems mentioned here were addressed, unfortunately I am not able to updated old SG releases, but since now on, they should be completely independent from VS extension.

**Comment by jons-bakerhill** [comment]
@NeVeSpl I pulled the latest and built locally. That fixed the ArgumentNullException. Any idea when the next release might be?

I suggest adding a build failing diagnostic (instead of the current warning diagnostics) when no templates are found along the lines of "No *.nt template files were found. Please make sure there is a template present in the project and its Build Action is set to C# analyzer additional file".  It doesn't make sense to me to have the source builder in a project and not be using it.

That last bit gets tricky when referencing files via "existing file links" as it jumps you to the actual file location if you left click on it, you have to right click first to be able to edit the link properties and set it as an additional file. Probably not worth adding that part to the error message as it's likely an uncommon scenario.

I have some hacked in diagnostics I *might* be able to create a PR for, but I'm already pushing the limits of the time I can spend on this at my employer.

Thanks for the responsiveness and quick fix!

**Comment by NeVeSpl** [comment]
Nuget is already published, for small fixes I usually do not do releases. 

Yeah, I am not fond of adding this failing diagnostics, I would prefer to level it as it is. The core of NT is shared between, SG, VS extension, and Blazor apps, I would prefer to keep it as end platform agnostic as possible.
