### ISSUE TITLE
Publish latest releases as NuGet package

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [NeVeSpl/NTypewriter#108]
Hi there,

I really want to use the latest releases of NTypewriter.SourceGenerator but there is no NuGet package available. When will 0.5.5 be available as NuGet package? Would you mind publishing a NuGet package with each release? 

So lonG

**Comment by NeVeSpl** [comment]
It is already published. But SG is versioned separately from the main library because I am releasing it more often. But there is always a version of SG using the latest version of NTypewriter available if that is possible.

**Comment by ViRuSTriNiTy** [comment]
Ah ok, so https://www.nuget.org/packages/NTypewriter.SourceGenerator/0.4.3 already contains the new lambda feature introduced in https://github.com/NeVeSpl/NTypewriter/releases/tag/v0.5.5?

**Comment by NeVeSpl** [comment]
I thought that I had made it clear in the announcement that it only works with the VS extension for now. For SG there is another problem with mismatching dll versions needed to compile lambdas.

**Comment by ViRuSTriNiTy** [comment]
> I thought that I had made it clear in the announcement that it only works with the VS extension for now. For SG there is another problem with mismatching dll versions needed to compile lambdas.

Oh, my bad. You made it clear but I did overlook the note, therefore issue closed. 🤐
