### ISSUE TITLE
Request - Property internal set vs public flag or filter 

### ISSUE THREAD

**Issue by jons-bakerhill** [NeVeSpl/NTypewriter#113]
Is there an equivalent to Symbols.ThatArePublic that could be used to check if a property has a public vs internal or private setter? I didn't see anything on https://github.com/NeVeSpl/NTypewriter/blob/master/NTypewriter.CodeModel/ISymbolBase.cs

**Comment by NeVeSpl** [comment]
I assume that `IPropertySymbol.IsReadOnly` is not what you need? I do not know how that happened, but only minimal info about properties is exposed, and even unit tests are missing for what is already exposed.  These shortcomings will definitely need to be completed.

**Comment by jons-bakerhill** [comment]
Even when setting the setter to private `IsReadOnly` is still false and `ThatArePublic` still includes it. E.g.
`public Guid? ForeignId { get; private set; }`
