### ISSUE TITLE
Should Types.ToTypeScriptType convert DateTime and DateTimeOffset to Date or string?

### ISSUE THREAD

**Issue by gregveres** [NeVeSpl/NTypewriter#13]
I see that Types.ToTypeScriptType converts a DateTime to a Date object. After years of working with Typewriter, C# and TS, I have come to the conclusion that the best practice is to define your TS interface interms of a string rather than Date. 

The issue marking the field as a Date object is that it isn't a date object. The back end will typically convert that DateTimeOffset or DateTime to a standardized string that javascript can parse. But when that field is read into memory, it is stored as a string. And you need to go through a separate step to create the Date object. And to top that off, the JS date constructor does not take a Date object as a parameter to its constructor, so the Typescript compiler complains that the statement creating the Date object is invalid, even though it will work at run time. 

Then when passing the date back to the api, you need to convert it to a string anyway. Again, you get Typescript compiler errors popping up because you are trying to set a Date object with a string value. 

I have had much better results making those date objects strings in the TS interface. Once I started doing that, everything worked out much, much better. The code was cleaner and typescript stopped complaining. 

So, I would recommend that Types.ToTypeScriptType should map DateTime and DateTimeOffset to strings.

**Comment by NeVeSpl** [comment]
Typewriter converts them to ``Date`` thus it will stay that way in NTypewriter too as default. But I see no reason why not to make it configurable as it was done in PR #7 with nullable types.

**Comment by gregveres** [comment]
Last night as I was comparing all the Urls created by NTypewriter to those created by Typewriter, I realized that I was wrong to request this "feature". I still believe that best practice is to pass dates between the front end and back end as strings and not DateTime/DateTimeOffset objects. But I remembered that you can't just "fix" it on the Typescript side, you have to make your DTO use string for those fields. My suggestion for best practice date handling is to never have your DTO include a DateTime or DateTimeOffset object, but instead use strings for those fields. This puts the proper handling of the conversion to and from the Date objects in your code's control, not hidden in some middleware. 

I have closed the PR and I am closing this. If someone feels this is necessary, then the PR is still there and can be modified to suit, but I don't feel this is necessary. Sorry for the noise.
