### ISSUE TITLE
Are you open to some negative Symbol filters?

### ISSUE THREAD

**Issue by gregveres** [NeVeSpl/NTypewriter#24]
I am still perfecting my Services generation template and I just realized that I have some Webhook Controllers that are being converted into Typescript Services because they are getting caught up in my data.Classes | Types.ThatInheritFrom query. 

I notice that all of your SymbolFunctions are positive and none are negative. I could use a Symbols.WhereNameSpaceDoesNobBeginWith query for instance, to filter out my Webhooks. 

I am willing to do a PR for some negative SymbolFunctions if you would like them as part of NTypewriter. 

I don't explicitly need it right now because I ended up doing an if with a continue in my loop. 

If I had the negative query, I would have done something like this:

`{{for controller in data.Classes | Types.ThatInheritFrom "OurBaseApiController" | Symbols.WhereNamespaceDoesNotStartsWith "path"}}
`

**Comment by NeVeSpl** [comment]
I am open to the concept of negative filters, but I need to think about how to expose them in the API.

**Comment by Tristan10** [comment]
I would also like to see negative symbol filters. Specifically Symbols.ThatDoNotHaveAttribute so that I can exclude certain classes when generating models.
