### ISSUE TITLE
Include System.Text.Json For Template Config

### ISSUE THREAD

**Issue by Tristan10** [NeVeSpl/NTypewriter#35]
Would you consider allowing the System.Text.Json NuGet package to be used in the compilation for the template config file? There's a mismatch between the result of String.ToCamelCase provided by this extension and the result of System.Text.Json.JsonNamingPolicy.CamelCase.ConvertName() which is the default in .NET Core. It causes issues when performing POST requests with the models generated by this extension.

Another option would be to utilize the above in the String.ToCamelCase method by default.

**Comment by NeVeSpl** [comment]
System.Text.Json will be available in version 0.1.11.
