### ISSUE TITLE
Feature/Docs Request - ability to output to a relative path outside VS solution

### ISSUE THREAD

**Issue by tomgruszowski** [NeVeSpl/NTypewriter#40]
.NET APIs and UI code are typically separated into repositories or folders.

Is there a way to configure the file output folder path to accomplish this?
i.e. given these folders Code\MyApiProject (c#) and Code\MyUI (html, typescript etc) 

Can I somehow specify an output filter path to be "../../MyUI"?

**Comment by NeVeSpl** [comment]
You can use whatever path you want (relative/absolute) in the save instruction:
```
{{ config.AddGeneratedFilesToVSProject = false
   capture output
       for class in data.Classes 
           class.FullName | String.Append "\r\n"
      end
   end
   Save output "../../MyUI/index.txt"
}} 
```
