### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Etchelon** [NeVeSpl/NTypewriter#41]
Hello!
First of all I want to say thanks for the effort you've put into this! It's not a small feat and it is tremendously helpful!

I've used TypeWriter some time ago, and I had assembled a nice set of scripts that allowed me to create TS interfaces from cs classes/enums and place them in various npm packages in the company ecosystem, and I am looking to translate those scripts into .nt scripts!
I used Attributes heavily in order to achieve that, so I'm trying to figure out how to do a few things:
1) Is there a way to use type hints in functions? I'm writing a lot of helpers like
```
func TsPropertyName(prop)
  ret prop.Name
end
```
but prop has no intellisense, and since I'm learning the tool it would ease the learning 10x

2) How can I log to the NTypewriter output? Would help a lot for debugging!
3) How can I throw exceptions?

Thanks!

**Comment by NeVeSpl** [comment]
The key is in ``[NTEditorFile]`` attribute, only files that contain decorated classes are detected and compiled. There is nothing about that in documentation, because I am not sure about that design. But if you decorate your classes with that attribute it should work.

**Comment by NeVeSpl** [comment]
As you can see, it is not exposed right now:
[SymbolBase.cs](/NeVeSpl/NTypewriter/blob/master/NTypewriter.CodeModel.Roslyn/SymbolBase.cs)
but it is available in Roslyn API:
[ISymbol.Locations](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.isymbol.locations?view=roslyn-dotnet-3.11.0#Microsoft_CodeAnalysis_ISymbol_Locations)
so if you want it, you need to create nice PR with tests and implementation. 😄
