### ISSUE TITLE
ERROR: System.NotImplementedException: The method or operation is not implemented.

### ISSUE THREAD

**Issue by DrPennybags** [NeVeSpl/NTypewriter#43]
I receive this error when rendering a template:

> ERROR: System.NotImplementedException: The method or operation is not implemented.
>    at EnvDTE.SourceControl.IsItemCheckedOut(String ItemName)
>    at NTypewriter.EditorForVisualStudio.Editor.SolutionItemsManager.Checkout(DTE2 dte, String filePath)
>    at NTypewriter.EditorForVisualStudio.NTypewriterEditorForVisualStudioPackage.<RenderTemplateCommand_OnExecuted>d__13.MoveNext()

Template:
```
{{ capture output
       for class in data.Classes 
           class.FullName | String.Append "\r\n"
      end
   end
   Save output "index.txt"
}}
```

The version of the extension is **0.2.0**.

**Comment by NeVeSpl** [comment]
That config line is about adding a file to a project, but VS has a problem with checking out the file from TFS/GIT, so it is not related.

What project is it? Consol app? asp net core 3.1? asp net mvc 5.0? Class library?

**Comment by NeVeSpl** [comment]
I do not know what is causing the problem, but since it is not essential functionality(checking out a file from source control), it will not stop rendering anymore. 
Version 0.2.1 of Editor is available.
