### ISSUE TITLE
[Question] Auto-render when C# file changes

### ISSUE THREAD

**Issue by xiluo58** [NeVeSpl/NTypewriter#47]
Will you add it in the future? If not, developers may forget to do it manually. Is there any method to make it auto or at least remind developers to do it manually? Method requires Visual Studio is fine.

**Comment by NeVeSpl** [comment]
What would you say about auto rendering after the project was successfully built? 
RenderOnBuild option soon will be added.

**Comment by xiluo58** [comment]
That would be perfect. Thanks for creating this useful tool.
