### ISSUE TITLE
Difference between the CLI tool and the VS Extension

### ISSUE THREAD

**Issue by Etchelon** [NeVeSpl/NTypewriter#54]
Hello again,
I'm building a CLI tool as per your guide, but I'm noticing differences in behavior.

For example, a class with nullable int properties ends up like this (correct) when I render via the VS extension:

![image](https://user-images.githubusercontent.com/4141889/151478265-e31459f1-8741-49c4-be80-1977c6849697.png)

and like this using the CLI tool:

![image](https://user-images.githubusercontent.com/4141889/151478354-f66b1cd0-b8af-480a-8a5e-67c979b661ef.png)

Do you have any quick insights on why this would be? The CLI tool's code is for the juicy part (code analyzer and compilation setup) the same you show in you example:

![image](https://user-images.githubusercontent.com/4141889/151478482-a79a6077-a904-4641-8c7e-e155ce1faab7.png)

**Comment by NeVeSpl** [comment]
VS extension relies on VS to make build, CLI relies on Buildalyzer to do that. It looks like to me that Buildalyzer is using a different and older version of msbuild/c# compiler than VS.

**Comment by Etchelon** [comment]
Ok thanks, make sense.
Another thing I noticed is that ISymbol.BaseClass is populated with `System.Object`...

**Comment by NeVeSpl** [comment]
But only in the CLI version, I hope?

**Comment by Etchelon** [comment]
Yes.
And the most annoying thing is that I'm referencing a ASP.NET web app as the project to analyze to the AnalyzerManager instance, and CodeModel.Classes does not contain any classes that are in that project, but just those in the referenced projects 🤔 
I guess it's not a question for you, but for Buildalyzer maintainers... anyway for the moment I'll have to use the VS extension until I sort the CLI tool out.

**Comment by Etchelon** [comment]
I have fixed my issue.
Simply by upgrading Buildalyzer to v4.x and passing to `manager.GetProject` the path to the whole solution and not the path to just the ASP.NET project.
