### ISSUE TITLE
doesnt work on VS 2019 , 16.10.x versions

### ISSUE THREAD

**Issue by alexeik** [NeVeSpl/NTypewriter#55]
plugin cant open own window on .nt editing...
nothings happen in output window except dump of version
on 16.11.x it works

typewriter works on 16.10.x

any diagnostic i can help?

**Comment by NeVeSpl** [comment]
Why do you need VS 16.10.x?  I guess the situation is similar to #44, at least 16.11.x is required ....

**Comment by alexeik** [comment]
because of WCF reference master was change in 16.11 and it works wierd.
i need to create WCF Client from VS and update them.

**Comment by alexeik** [comment]
so, will it work?
