### ISSUE TITLE
Disabling preview?

### ISSUE THREAD

**Issue by SimmeNilsson** [NeVeSpl/NTypewriter#60]
Is is possible to disable the preview window in the editor?
I don't always need it and it seems to take a decent time spinning up when opening the .nt file.

**Comment by NeVeSpl** [comment]
[Documentation -> Visual Studio Configuration -> Live preview](https://github.com/NeVeSpl/NTypewriter/blob/master/Documentation/VisualStudioConfiguration.md)

**Comment by SimmeNilsson** [comment]
Great! Thank you!
