### ISSUE TITLE
Support for JetBrains Rider

### ISSUE THREAD

**Issue by rmarskell** [NeVeSpl/NTypewriter#64]
I know this is a long shot, but is there any chance this could be ported to [JetBrains Rider](https://www.jetbrains.com/rider/) as a plug-in? I don't know what kind of a lift it is to port a VS extension to a Rider plug-in, but I would love to use this in Rider.

**Comment by NeVeSpl** [comment]
Rider is based on IntelliJ IDE which runs on JVM, UI plug-ins are written in Kotlin, and the extensibility model is entirely different from VS. So there would not be much to port, a whole .nt editor would have to be created from the beginning. 

The same story is with VSCode.

NTypewrite is CLI capable, thus anyone can try to write an editor for it for any IDE. I have no skill or intention to write one for Rider, the one for VSC always was in plans, so maybe someday it will be released.

**Comment by rmarskell** [comment]
Ah, ok. That's what I figured.

Would it be possible to just create/edit the templates in VS, but have the actual generation run via an msbuild task / nuget package / something so it could generate elsewhere (Rider, CLI, etc.)? (Please forgive my ignorance. 😅)

**Comment by NeVeSpl** [comment]
Yes, there is a chapter about that in the manual:
[Build your own CLI](https://github.com/NeVeSpl/NTypewriter/blob/master/Documentation/CLI.md)

also, there was a try in past to provide a generic CLI, but apparently the project has died:
 https://github.com/TietoEVRY/NTypewriterCLI
