### ISSUE TITLE
IType.IsCollection returns false for IList<T>

### ISSUE THREAD

**Issue by Xriuk** [NeVeSpl/NTypewriter#65]
Type:
```
IList<MyClass> or IList<MyClass>?
```
the result is the same

AllInterfaces print:
```
[ICollection<MyClass>, IEnumerable<MyClass>, IEnumerable]
```

It returns `false` for `IType.IsCollection` but `true` for `IType.IsEnumerable`

I think here:
https://github.com/NeVeSpl/NTypewriter/blob/96354ef3e5a38856e09daaccf417a44688f841bc/NTypewriter.CodeModel.Roslyn/Type.cs#L17
should become something like:
```csharp
public bool IsCollection => symbol.AllInterfaces.Any(x => x.ToString() == "System.Collections.ICollection" || x.ToString().StartsWith("System.Collections.Generic.ICollection")) || this.FullName.StartsWith("System.Collections.Generic.ICollection") || this.FullName == "System.Collections.ICollection";
```

**Comment by NeVeSpl** [comment]
Indeed, you are right.
