### ISSUE TITLE
extracting argument from attribute now fails

### ISSUE THREAD

**Issue by gregveres** [NeVeSpl/NTypewriter#88]
I accidentally upgraded to the lastest version of NTypewriter and my scripts started failing. 
I have narrowed it down to this custom function:
```
        public static string ExtractTypescriptType(IAttribute attr)
        {
            if (attr.Name == "TypescriptType")
            {
                var attrType = attr.Arguments.FirstOrDefault()?.Value;
                if (attrType != null) return attrType as string;
            }

            return string.Empty;
        }
```

The failure happens with the statement ```return attrType as string;```.
In previous versions this used to properly take the attrType and convert it to a string and return it. In the lastest version this always returns null.

In the debugger, I can see that attrType is of type: 
For more context, the IAttribute is ```object {NTypewriter.CodeModel.Roslyn.TypedConstant}``` with a value of "string|null" and a type of ```{string}```

I am defining the attribute in my project like this:
```
    /// <summary>
    ///     Indicates the type that should be used for this class property or class when exporting to typescript.
    ///     [TypescriptType(type = "string?")] for example this makes the property or every instance of the class
    ///     an optional string
    /// </summary>
    [AttributeUsage(AttributeTargets.Property | AttributeTargets.Class)]
    public class TypescriptType: Attribute
    {
        public string Type { get; set; }

        public override string ToString()
        {
            return Type;
        }
    }
```
In the Summary text you can see how it is used. 

It looks like I used to be on version 0.4.1 and I have upgraded to 0.4.4.

**Comment by NeVeSpl** [comment]
There was a breaking change, `IAttributeArgument.Value` is now of `ITypedConstant` or `ITypedConstant[]`.

So, smth like that should work:
```csharp
public static string ExtractTypescriptType(IAttribute attr)
{
    if (attr.Name == "TypescriptType")
    {
        var attrType = attr.Arguments.FirstOrDefault()?.Value as ITypedConstant;
        if (attrType != null) return attrType.Value as string;
    }

    return string.Empty;
}
```

**Comment by gregveres** [comment]
Yes, thanks. I just figured that out and changed my code to something very similar to this. I was about to post something similar.

**Comment by NeVeSpl** [comment]
[Debug.WriteLine](https://github.com/NeVeSpl/NTypewriter/blob/master/Documentation/BuiltInFunctions.md#writeline)

Version 0.4.4.1 with fixed null reference problem is published.

**Comment by gregveres** [comment]
closing since this is due toa  breaking change that can be handled in my code.
