### ISSUE TITLE
FR: please include the vsix package file in the list of assets for the release. 

### ISSUE THREAD

**Issue by gregveres** [NeVeSpl/NTypewriter#90]
As I am realizing, it is impossible to rollback to a previous version of Ntypewriter because there is no location where I can get the previous version of the vsix file. Visual Studio doesn't have version management built in for extensions so I think what we need to be able to roll back is access to older vsix files. 

Can you please start including the vsix file in the list of assets with each release? That would allow us to roll back if we run into an issue that is a show stopper like there is in 0.4.4.

**Comment by gregveres** [comment]
I am back in action. I had 0.4.3 on my laptop so I was able to copy that over to my main dev machine. So, there is no rush to fix 0.4.4 on my account. 0.4.3 works great for now.

**Comment by NeVeSpl** [comment]
The newest version will always be available only on the marketplace, but I will try to include the previous version when doing a release.
