### ISSUE TITLE
Template processing fails when reading arguments from an Attribute that has arguments with default values (Roslyn project)

### ISSUE THREAD

**Issue by dbuvid** [NeVeSpl/NTypewriter#97]
An attribute with a signature with a default value argument, i.e.
public SomeAttribute(string arg1, string arg2 = null)

With the usage

[Some("arg1Value"]

Causes an exception to be thrown when you attempt to access the Arguments property on the IAttribute model.

https://github.com/NeVeSpl/NTypewriter/blob/98fbb168afe3d394862b8bae299c8741853ac968/NTypewriter.CodeModel.Roslyn/Attribute.cs#L46C50-L46C70 is the root cause; defaulted arguments are not included in the ConstructorArguments array.

As a workaround I have just been explicitly passing these parameters in the necessary attributes.

**Comment by NeVeSpl** [comment]
Are you sure about that? 

I have added unit test that shows there is no problem with handling default value for arguments.

**Comment by dbuvid** [comment]
Hmm, must be something I'm doing wrong -- I was attempting to write my own CLI but I determined just using the extension will meet my requirements.

I'm using the same C# custom functions for both the CLI and extension but the scenario works fine with the extension.

**Comment by NeVeSpl** [comment]
Unfortunately there are small discrepancies in the data obtained through Roslyn API, between CLI and VS extension. VS is doing perfect job in compiling solution, and getting the same results even with the help of Buildalyzer is not easy.
